
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author bruno
 */
public class Guia extends javax.swing.JFrame {
    
    ImageIcon icon0, icon1, icon2, icon3, icon4, icon5, icon6, icon7, icon8, icon9, icon10, icon11, icon12, icon13, icon14; 

    /**
     * Creates new form Guia
     */
    public Guia() {
        initComponents();
        icon0 = new ImageIcon("D:\\MipsSim\\MipSim\\src\\Imagens\\Guia_de_usuario-01.png");
        icon1 = new ImageIcon("D:\\MipsSim\\MipSim\\src\\Imagens\\Guia_de_usuario-02.png");
        icon2 = new ImageIcon("D:\\MipsSim\\MipSim\\src\\Imagens\\Guia_de_usuario-03.png");
        icon3 = new ImageIcon("D:\\MipsSim\\MipSim\\src\\Imagens\\Guia_de_usuario-04.png");
        icon4 = new ImageIcon("D:\\MipsSim\\MipSim\\src\\Imagens\\Guia_de_usuario-05.png");
        icon5 = new ImageIcon("D:\\MipsSim\\MipSim\\src\\Imagens\\Guia_de_usuario-06.png");
        icon6 = new ImageIcon("D:\\MipsSim\\MipSim\\src\\Imagens\\Guia_de_usuario-07.png");
        icon7 = new ImageIcon("D:\\MipsSim\\MipSim\\src\\Imagens\\Guia_de_usuario-08.png");
        icon8 = new ImageIcon("D:\\MipsSim\\MipSim\\src\\Imagens\\Guia_de_usuario-09.png");
        icon9 = new ImageIcon("D:\\MipsSim\\MipSim\\src\\Imagens\\Guia_de_usuario-10.png");
        icon10 = new ImageIcon("D:\\MipsSim\\MipSim\\src\\Imagens\\Guia_de_usuario-11.png");
        icon11 = new ImageIcon("D:\\MipsSim\\MipSim\\src\\Imagens\\Guia_de_usuario-12.png");
        icon12 = new ImageIcon("D:\\MipsSim\\MipSim\\src\\Imagens\\Guia_de_usuario-13.png");
        icon13 = new ImageIcon("D:\\MipsSim\\MipSim\\src\\Imagens\\Guia_de_usuario-14.png");
        icon14 = new ImageIcon("D:\\MipsSim\\MipSim\\src\\Imagens\\Guia_de_usuario-15.png");
        img.setIcon(icon0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        img = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Guia_de_usuario-01.png"))); // NOI18N
        jScrollPane1.setViewportView(img);

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("<<");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setText(">>");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1669, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(1766, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(16, 16, 16)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(416, 416, 416))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1002, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(549, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(418, 418, 418)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (img.getIcon()==icon14){
            img.setIcon(icon13);
        }else if (img.getIcon()==icon13){
            img.setIcon(icon12);
        }else if (img.getIcon()==icon12){
            img.setIcon(icon11);
        }else if (img.getIcon()==icon11){
            img.setIcon(icon10);
        }else if (img.getIcon()==icon10){
            img.setIcon(icon9);
        }else if (img.getIcon()==icon9){
            img.setIcon(icon8);
        }else if (img.getIcon()==icon8){
            img.setIcon(icon7);
        }else if (img.getIcon()==icon7){
            img.setIcon(icon6);
        }else if (img.getIcon()==icon6){
            img.setIcon(icon5);
        }else if (img.getIcon()==icon5){
            img.setIcon(icon4);
        }else if (img.getIcon()==icon4){
            img.setIcon(icon3);
        }else if (img.getIcon()==icon3){
            img.setIcon(icon2);
        }else if (img.getIcon()==icon2){
            img.setIcon(icon1);
        }else if (img.getIcon()==icon1){
            img.setIcon(icon0);
        }else if (img.getIcon()==icon0){
            img.setIcon(icon14);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (img.getIcon()==icon0){
            img.setIcon(icon1);
        }else if (img.getIcon()==icon13){
            img.setIcon(icon14);
        }else if (img.getIcon()==icon12){
            img.setIcon(icon13);
        }else if (img.getIcon()==icon11){
            img.setIcon(icon12);
        }else if (img.getIcon()==icon10){
            img.setIcon(icon11);
        }else if (img.getIcon()==icon9){
            img.setIcon(icon10);
        }else if (img.getIcon()==icon8){
            img.setIcon(icon9);
        }else if (img.getIcon()==icon7){
            img.setIcon(icon8);
        }else if (img.getIcon()==icon6){
            img.setIcon(icon7);
        }else if (img.getIcon()==icon5){
            img.setIcon(icon6);
        }else if (img.getIcon()==icon4){
            img.setIcon(icon5);
        }else if (img.getIcon()==icon3){
            img.setIcon(icon4);
        }else if (img.getIcon()==icon2){
            img.setIcon(icon3);
        }else if (img.getIcon()==icon1){
            img.setIcon(icon2);
        }else if (img.getIcon()==icon14){
            img.setIcon(icon0);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel img;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
